### ISSUE TITLE
Add support for jsonnet-bundler files

### ISSUE THREAD

**Issue by mjpitz** [depscloud/depscloud#115] opened 2020-10-13 01:49 UTC
* File name: `jsonnetfile.json`
* Language: `jsonnet`
* For git sources:
  * The `name` should be formatted as `{{ remote }}[#{{ subdir }}]` where `subdir` is
    * the directory path in the repository we're indexing (for modules produced by a repo)
    * the attribute as specified in dependencies

Example File:

```
{
  "version": 1,
  "dependencies": [
    {
      "source": {
        "git": {
          "remote": "https://github.com/grafana/grafonnet-lib.git",
          "subdir": "grafonnet"
        }
      },
      "version": "master"
    },
    {
      "source": {
        "git": {
          "remote": "https://github.com/grafana/jsonnet-libs.git",
          "subdir": "grafana-builder"
        }
      },
      "version": "master"
    }
  ],
  "legacyImports": false
}
```

Design Doc: https://docs.google.com/document/d/1czRScSvvOiAJaIjwf3CogOULgQxhY9MkiBKOQI1yR14/edit

**Comment by Redaloukil** [comment] 2020-10-17 22:35
@mjpitz  Hi, I was looking for noob contribution as a starter and I found my self here, still cannot understand what i'm supposed to do for this issue, i'll appreciate to be helped by you and I prefer to start with my understanding of what the issue is about :
- the `jsonnetfile`  you are mentioning seems to be the output specifying the dependencies of a project.
- The extractor is the part of the architecture which is supposed to resolve the dependencies and generate the` jsonnetfile`.
( please give me more details about how the process of generating this `jsonnetfile` work.
My questions are : 
- Where is module where `jsonnetfile` is generated ? 
- Can you elaborate more on what i should do ?
And finally, can you please assign to this issue ?

**Comment by mjpitz** [comment] 2020-10-18 14:35
Hey @Redaloukil ,

So, the `jsonnetfile` is something that would be commit to a repository like many other manifest files (e.g. `package.json`, `pom.xml`, etc). The extractor process is responsible for identifying these files and extracting their contents into a common structure for the system. You can find an example `jsonnetfile.json` in our [depscloud/deploy](https://github.com/depscloud/deploy) repository under the `monitoring` folder.

**Closed** 2020-12-12 05:27 UTC
Labels: effort: 3, good first issue, hacktoberfest, help, type: feature
